version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    resource_class: xlarge
    environment:
      JVM_OPTS: -Xmx4096m
      GRADLE_MAX_PARALLEL_FORKS: 2
    steps:
      - checkout
      - run:
          name: Calculate Cache Hash
          command: |
            find . \( -name \*.gradle -or -name \*.groovy -or -name \*.sh -or -name \*.rb -or -name circle.yml \) -exec shasum {} \; | sort > .cache-hash
            cat .cache-hash
      - run:
          name: Install Maven
          command: sudo apt-get update; sudo apt-get install maven
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Download Dependencies
          command: |
            sdkmanager --install 'platforms;android-27'
            sdkmanager --install 'platforms;android-P'
            ./scripts/install-dependencies.rb
            ./gradlew prefetchDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - /opt/android/sdk/platforms/android-27
            - /opt/android/sdk/platforms/android-P
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Build
          command: SKIP_JAVADOC=true ./gradlew clean assemble --info --stacktrace
      - run:
          name: Test 1/2
          command: |
            SKIP_JAVADOC=true ./gradlew test --info --stacktrace --continue \
                -Drobolectric.enabledSdks=16,17,18,19,21 -Drobotests.binResultsDir=shard1 \
                -Drobolectric.alwaysIncludeVariantMarkersInTestName=true
      - run:
          name: Test 2/2
          command: |
            SKIP_JAVADOC=true ./gradlew test --info --stacktrace --continue \
                -Drobolectric.enabledSdks=22,23,24,25,26 -Drobotests.binResultsDir=shard2 \
                -Drobolectric.alwaysIncludeVariantMarkersInTestName=true
      - run:
          name: Collect Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports
      - run:
          name: Upload Snapshot
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew upload --no-rebuild
            fi
